name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up pixi"
              uses: prefix-dev/setup-pixi@v0.9.6
              with:
                  environments: coverage

            - name: "Check code coverage"
              run: |
                  pixi run -e coverage coverage

            - name: "Coveralls"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  pixi run -e coverage coveralls --service=github

    lint:
        name: "Code style"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up pixi"
              uses: prefix-dev/setup-pixi@v0.9.6
              with:
                  environments: default

            - name: "Lint code"
              run: |
                  pixi run lint

    test:
        name: "Test ${{ matrix.os }} with ${{ matrix.environment }}"
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                environment: [py39, py310, py311, py312]

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up pixi"
              uses: prefix-dev/setup-pixi@v0.9.6
              with:
                  environments: ${{ matrix.environment }}

            - name: "Run unit tests"
              run: |
                  pixi run -e ${{ matrix.environment }} test
