name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    lint:
        name: "Code style"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Set up Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox tox-gh-actions

            - name: "Check code format"
              run: |
                  tox -e lint
